// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD08tpZSrrcin8rqKSoCyTmI2DRgZKWl20',
    appId: '1:40815536348:web:0dd80c3e8a416e07d5ac19',
    messagingSenderId: '40815536348',
    projectId: 'receiptify-7ff3f',
    authDomain: 'receiptify-7ff3f.firebaseapp.com',
    storageBucket: 'receiptify-7ff3f.firebasestorage.app',
    measurementId: 'G-S3NKM7MD8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU7Q6v_LT04JIEPjsoJUKSD2N-7DZrGHk',
    appId: '1:40815536348:android:7323f96d9d760ecbd5ac19',
    messagingSenderId: '40815536348',
    projectId: 'receiptify-7ff3f',
    storageBucket: 'receiptify-7ff3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjPaYsljiIWib-yeW7w6olDj-DDnVL41M',
    appId: '1:40815536348:ios:bac81ae4ad7cc3edd5ac19',
    messagingSenderId: '40815536348',
    projectId: 'receiptify-7ff3f',
    storageBucket: 'receiptify-7ff3f.firebasestorage.app',
    iosBundleId: 'com.example.receiptify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjPaYsljiIWib-yeW7w6olDj-DDnVL41M',
    appId: '1:40815536348:ios:bac81ae4ad7cc3edd5ac19',
    messagingSenderId: '40815536348',
    projectId: 'receiptify-7ff3f',
    storageBucket: 'receiptify-7ff3f.firebasestorage.app',
    iosBundleId: 'com.example.receiptify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD08tpZSrrcin8rqKSoCyTmI2DRgZKWl20',
    appId: '1:40815536348:web:fd734c6259d707d4d5ac19',
    messagingSenderId: '40815536348',
    projectId: 'receiptify-7ff3f',
    authDomain: 'receiptify-7ff3f.firebaseapp.com',
    storageBucket: 'receiptify-7ff3f.firebasestorage.app',
    measurementId: 'G-PWLPL4K3F6',
  );
}
